language: scala
scala:
  - 2.12.2
  
services:
  - docker

jdk:
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION receptor/docker:publishLocal;

after_success:
  - if [ "$TRAVIS_BRANCH" == "testing" ]; then
    docker container ls;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$DOCKER_HUB_ORG"/receptor:1.0;
    fi
