version: '2'
services:
  seed:
    image: repositorioweb:1.0
    ports:
      - '9000:9000'
    environment:
      REPSEG_DIRECTORIO_EXCEL: /Users/utaladriz/repositorio/receptorExcelEntrada
      REPSEG_DIRECTORIO_LOG: /Users/utaladriz/repositorio/receptorDTEntrada
      REPSEG_HOST_POSTGRES: 192.168.1.85
      REPSEG_PWD_POSTGRES: repo_adm
      REPSEG_USR_POSTGRES: repo_adm
      REPSEG_URL_CALLBACK: https://54.187.41.133:8080/callback
      REPSEG_PRODUCCION: true
